name: Healthz integration test
on: [pull_request]

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download

      - name: Check Go version
        run: go version

      - name: Set .env file
        run: |
          touch .env
          echo DBHOST="localhost" >> .env
          echo DBUSER="postgres" >> .env
          echo DBPASSWORD="postgres" >> .env
          echo DBNAME="postgres" >> .env
          echo DBPORT="5433" >> .env
          echo SERVERPORT=":8080" >> .env
          cat .env

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-client
          sudo service postgresql start
          pg_isready
