name: Healthz integration test
on: [pull_request]

jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download

      - name: Check Go version
        run: go version

      - name: Set .env file
        run: |
          touch .env
          echo DBHOST="localhost" >> .env
          echo DBUSER="pguser" >> .env
          echo DBPASSWORD="pguser" >> .env
          echo DBNAME="csye6225_db" >> .env
          echo DBPORT="5432" >> .env
          echo SERVERPORT=":8080" >> .env
          ls -la

#      - name: Set up PostgreSQL
#        run: |
#          sudo apt-get update
#          sudo apt-get install postgresql postgresql-client
#          sudo service postgresql start
#          pg_isready

      - name: Create PG user and database
        run: |
          # Load environment variables from .env file
          source .env
          sudo -u postgres psql --command="CREATE USER $DBUSER PASSWORD '$DBPASSWORD'" --command="\du"
          sudo -u postgres psql --command="CREATE DATABASE $DBNAME OWNER $DBUSER" --command="\l"
          PGPASSWORD=$DBPASSWORD psql -U $DBUSER -d $DBNAME -h $DBHOST -p $DBPORT

      - name: run integration test
        run: go test ./integration_tests/

