name: Healthz integration test
on: [pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          check-latest: true

      - name: Install dependencies
        run: |
          go mod download

      - name: Check Go version
        run: go version

      - name: Set up PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install postgresql postgresql-client
          sudo service postgresql start
          pg_isready

      - name: Updating database user
        env:
          DBUSER: ${{ secrets.APP_DBUSER }}
          DBPASSWORD: ${{ secrets.APP_DBPASSWORD }}
        run: |
          sudo -u postgres psql -c "ALTER ROLE $DBUSER WITH PASSWORD '$DBPASSWORD';"

      - name: run integration test
        env:
          DBHOST: ${{ secrets.APP_DBHOST }}
          DBUSER: ${{ secrets.APP_DBUSER }}
          DBPASSWORD: ${{ secrets.APP_DBPASSWORD }}
          DBNAME: ${{ secrets.APP_DBNAME }}
          DBPORT: ${{ secrets.APP_DBPORT }}
        run: go test ./integration_tests/

