name: Healthz integration test
run-name: Integration test for healthz endpoint
on: [pull_request]
      
jobs:
  Run-Integration-test-for-healthz:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!!!"
