name: Packer fmt & validate
on: [pull_request]

jobs:
  packer-fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup build location
        run: |
          mkdir builds
          touch ./builds/webapp.tar
          ls -la ./builds

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Run `packer init`
        id: init
        run: "packer init ./packer/debian12-ami.pkr.hcl"

      - name: Run `packer fmt`
        id: fmt
        run: "packer fmt -check ./packer/debian12-ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        env:
          PKR_AWS_REGION: ${{ vars.PKR_AWS_REGION }}
          PKR_AWS_SRC_AMI: ${{ vars.PKR_AWS_SRC_AMI }}
          PKR_AWS_SSH_USERNAME: ${{ vars.PKR_AWS_SSH_USERNAME }}
          PKR_AWS_SUBNET: ${{ vars.PKR_AWS_SUBNET }}
          APP_DBHOST: ${{ secrets.APP_DBHOST }}
          APP_DBUSER: ${{ secrets.APP_DBUSER }}
          APP_DBPASSWORD: ${{ secrets.APP_DBPASSWORD }}
          APP_DBNAME: ${{ secrets.APP_DBNAME }}
          APP_DBPORT: ${{ secrets.APP_DBPORT }}
          APP_SERVERPORT: ${{ secrets.APP_SERVERPORT }}
          APP_DEFAULT_USERS_LOC: ${{ secrets.APP_DEFAULT_USERS_LOC }}
        run: "packer validate ./packer/debian12-ami.pkr.hcl"