name: Packer fmt & validate
on: [pull_request]

jobs:
  packer-fmt-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: 'latest'

      - name: Run `packer init`
        id: init
        run: "packer init -check ./packer/debian12-ami.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./packer/debian12-ami.pkr.hcl"